### ISSUE TITLE
HX711 Standalone

### ISSUE THREAD

**Issue by Priya003** [sparkfun/HX711-Load-Cell-Amplifier#9]
Hi, wanted to use HX711 24-bit adc standalone to measure voltage range of 2mv - 20mv.
Problem is:
1) I cannot interpret the adc output count.
2) What should i do in my code(code below) so that it prints voltages not decimal values.
Tried with different values of voltages(shared below), and i am totally confused with the readings. I don't know how to convert these values in voltage. What is the logic behind. Please help!
Readings:
0mv --- 5219
1.1mv --- 5095
2.3mv --- 4981
2.5mv --- 4960
2.9mv --- 4918
5mv --- 4693
10.6mv --- 4075
15.1mv --- 3597
22.7mv --- 2700
40.7mv --- 562
5volts --- -8388608
-5volts --- -8388607
Board is arduino leonardo, and a simple voltage divider is used for voltage generation(for testing only). The voltages are measured and calculated from multimeter and hand calculations. I need HX711 do this for me. What is the differential ADC count and voltage relationship...?
A bogde/HX711 library is used: https://github.com/bogde/HX711
Code:
`#include "HX711.h"
#define DOUT 3
#define CLK 2
HX711 scale(DOUT, CLK);
void setup() {
Serial.begin(115200);
}
void loop() {
long avg = scale.get_value(60);
Serial.print("Digital Code = ");
Serial.println(avg);
}`
![Circuit_diagram](https://cloud.githubusercontent.com/assets/20499910/16924515/54eb8efa-4d3d-11e6-8f79-cc0f5655a4ce.jpg)

**Comment by BrentWilkins** [comment]
[Here](https://learn.sparkfun.com/tutorials/load-cell-amplifier-hx711-breakout-hookup-guide) is our documentation on our HX711 Breakout. We don't necessarily support 3rd party code. If you have more questions, please try asking in our [forums]9https://forum.sparkfun.com/) or our tech support team.

**Comment by robwyatt** [comment]
I would suggest the hx711 is not the correct part for what you are trying to do. At best case you are way out of spec because its going to expect A+ and A- to be very close and somewhere near the half way point of E+ and E-, its not going to expect one of them to be grounded even if the voltage between them is only 20mv. More complex load cell systems would go in to error more if you did this because they sense it as a short circuit. The Sparkfun board also uses the built in voltage regulator so E+ is not simply VCC, E+ is being driven by the PNP transistor, via the base and feedback pins on the hx711 and I haven't really looked at what that pin does and I can't even speculate what it does if you ground one of the inputs. 

If you have a single ended input I would suggest one of the many ADCs out there that will measure 20mv, at worst case use an op amp to condition the input. 

If you want to use this in an esoteric way then you really have to start with a resistor bridge, get valid readings and then manipulate the bridge and resistor values until you get something you can use and that makes sense.
